CREATE DATABASE IF NOT EXISTS movie_and_game_reviewer;

DROP TABLE IF EXISTS _user CASCADE;
CREATE TABLE _user (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	firstName VARCHAR(255),
	lastName VARCHAR(255),
	email VARCHAR(255),
	password VARCHAR(20),
	birth_date DATE,
	registration_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	_user_group_id bigint,
	review_id bigint,
	CONSTRAINT _user_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS _user_group CASCADE;
CREATE TABLE _user_group (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	group_name VARCHAR(20),
	_user_id bigint,
	CONSTRAINT _user_group_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS movie_genre CASCADE;
CREATE TABLE movie_genre (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
	movie_id bigint,
	CONSTRAINT movie_genre_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS game_genre CASCADE;
CREATE TABLE game_genre (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
	game_id bigint,
	CONSTRAINT game_genre_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS _language CASCADE;
CREATE TABLE _language (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50),
	game_id bigint,
	movie_id bigint,
	CONSTRAINT _language_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS person CASCADE;
CREATE TABLE person (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	birth_date DATE,
	CONSTRAINT person_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS director CASCADE;
CREATE TABLE director (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	person_id bigint,
	movie_id bigint,
	game_id bigint,
	CONSTRAINT director_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS actor CASCADE;
CREATE TABLE actor (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	person_id bigint,
	movie_id bigint,
	game_id bigint,
	CONSTRAINT actor_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS rate CASCADE;
CREATE TABLE rate (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(20),
	movie_id bigint,
	game_id bigint,
	CONSTRAINT rate_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS information CASCADE;
CREATE TABLE information (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	title VARCHAR(255),
	description VARCHAR(500),
	release_date DATE,
	budget INT,
	rate_id bigint,
	_language_id bigint,
	review_id bigint,
	director_id bigint,
	actor_id bigint,
	CONSTRAINT information_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS movie CASCADE;
CREATE TABLE movie (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	movie_length INT,
	information_id bigint,
	movie_genre_id bigint,
	CONSTRAINT movie_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS game CASCADE;
CREATE TABLE game (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	information_id bigint,
	game_genre_id bigint,
	CONSTRAINT game_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS review CASCADE;
CREATE TABLE review (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	description varchar(500),
	_user_id bigint,
	game_id bigint,
	movie_id bigint,
	CONSTRAINT review_id PRIMARY KEY(id)
);

ALTER TABLE _user ADD CONSTRAINT _user_group
	FOREIGN KEY (_user_group_id)
	REFERENCES _user_group (id);

ALTER TABLE _user ADD CONSTRAINT review
	FOREIGN KEY (review_id)
	REFERENCES review (id);
	
ALTER TABLE _user_group ADD CONSTRAINT _user
	FOREIGN KEY (_user_id)
	REFERENCES _user (id);

ALTER TABLE movie_genre ADD CONSTRAINT movie
	FOREIGN KEY (movie_id)
	REFERENCES movie (id);
	
ALTER TABLE game_genre ADD CONSTRAINT game
	FOREIGN KEY (game_id)
	REFERENCES game (id);

ALTER TABLE _language ADD CONSTRAINT game
	FOREIGN KEY (game_id)
	REFERENCES game (id);
	
ALTER TABLE _language ADD CONSTRAINT movie
	FOREIGN KEY (movie_id)
	REFERENCES movie (id);
	
ALTER TABLE director ADD CONSTRAINT person
	FOREIGN KEY (person_id)
	REFERENCES person (id);

ALTER TABLE director ADD CONSTRAINT game
	FOREIGN KEY (game_id)
	REFERENCES game;
	
ALTER TABLE director ADD CONSTRAINT movie
	FOREIGN KEY (movie_id)
	REFERENCES movie (id);
	
ALTER TABLE actor ADD CONSTRAINT person
	FOREIGN KEY (person_id)
	REFERENCES person (id);
	
ALTER TABLE actor ADD CONSTRAINT movie
	FOREIGN KEY (movie_id)
	REFERENCES movie (id);
	
ALTER TABLE actor ADD CONSTRAINT game
	FOREIGN KEY (game_id)
	REFERENCES game;
	
ALTER TABLE rate ADD CONSTRAINT movie
	FOREIGN KEY (movie_id)
	REFERENCES movie (id);
	
ALTER TABLE rate ADD CONSTRAINT game
	FOREIGN KEY (game_id)
	REFERENCES game (id);

ALTER TABLE information ADD CONSTRAINT rate
	FOREIGN KEY (rate_id)
	REFERENCES rate (id);

ALTER TABLE information ADD CONSTRAINT _language
	FOREIGN KEY (_language_id)
	REFERENCES _language (id);
	
ALTER TABLE information ADD CONSTRAINT review
	FOREIGN KEY (review_id)
	REFERENCES review (id);
	
ALTER TABLE information ADD CONSTRAINT director
	FOREIGN KEY (director_id)
	REFERENCES director (id);

ALTER TABLE information ADD CONSTRAINT actor
	FOREIGN KEY (actor_id)
	REFERENCES actor (id);
	
ALTER TABLE movie ADD CONSTRAINT information
	FOREIGN KEY (information_id)
	REFERENCES information (id);
	
ALTER TABLE movie ADD CONSTRAINT movie_genre
	FOREIGN KEY (movie_genre_id)
	REFERENCES movie_genre (id);

ALTER TABLE game ADD CONSTRAINT information
	FOREIGN KEY (information_id)
	REFERENCES information (id);
	
ALTER TABLE game ADD CONSTRAINT game_genre
	FOREIGN KEY (game_genre_id)
	REFERENCES game_genre (id);
	
ALTER TABLE review ADD CONSTRAINT _user
	FOREIGN KEY (_user_id)
	REFERENCES _user (id);
	
ALTER TABLE review ADD CONSTRAINT movie
	FOREIGN KEY (movie_id)
	REFERENCES movie (id);

ALTER TABLE review ADD CONSTRAINT game
	FOREIGN KEY (game_id)
	REFERENCES game (id);