CREATE DATABASE IF NOT EXISTS movie_and_game_reviewer;

DROP TABLE IF EXISTS _user CASCADE;
CREATE TABLE _user (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	email VARCHAR(255),
	password VARCHAR(20),
	birth_date DATE,
	registration_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	_user_group bigint,
	CONSTRAINT _user_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS _user_group CASCADE;
CREATE TABLE _user_group (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(20),
	CONSTRAINT _user_group_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS movie_genre CASCADE;
CREATE TABLE movie_genre (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
	CONSTRAINT movie_genre_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS game_genre CASCADE;
CREATE TABLE game_genre (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(30),
	CONSTRAINT game_genre_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS _language CASCADE;
CREATE TABLE _language (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(50),
	CONSTRAINT _language_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS person CASCADE;
CREATE TABLE person (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	first_name VARCHAR(255),
	last_name VARCHAR(255),
	birth_date DATE,
	CONSTRAINT person_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS director CASCADE;
CREATE TABLE director (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	person bigint,
	CONSTRAINT director_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS actor CASCADE;
CREATE TABLE actor (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	person bigint,
	CONSTRAINT actor_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS rate CASCADE;
CREATE TABLE rate (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(20),
	CONSTRAINT rate_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS information CASCADE;
CREATE TABLE information (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	title VARCHAR(255),
	description VARCHAR(500),
	release_date DATE,
	budget INT,
	rate bigint,
	_language bigint,
	review bigint,
	director bigint,
	CONSTRAINT information_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS movie CASCADE;
CREATE TABLE movie (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	movie_length INT,
	information bigint,
	movie_genre bigint,
	CONSTRAINT movie_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS game CASCADE;
CREATE TABLE game (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	information bigint,
	game_genre bigint,
	CONSTRAINT game_pk PRIMARY KEY(id)
);

DROP TABLE IF EXISTS review CASCADE;
CREATE TABLE review (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	description varchar(500),
	_user bigint,
	game bigint,
	movie bigint,
	CONSTRAINT review_id PRIMARY KEY(id)
);

ALTER TABLE _user ADD CONSTRAINT _user_group
	FOREIGN KEY (_user_group)
	REFERENCES _user_group (id);
	
ALTER TABLE director ADD CONSTRAINT person
	FOREIGN KEY (person)
	REFERENCES person (id);
	
ALTER TABLE actor ADD CONSTRAINT person
	FOREIGN KEY (person)
	REFERENCES person (id);

ALTER TABLE information ADD CONSTRAINT rate
	FOREIGN KEY (rate)
	REFERENCES rate (id);

ALTER TABLE information ADD CONSTRAINT _language
	FOREIGN KEY (_language)
	REFERENCES _language (id);
	
ALTER TABLE information ADD CONSTRAINT review
	FOREIGN KEY (review)
	REFERENCES review (id);
	
ALTER TABLE information ADD CONSTRAINT director
	FOREIGN KEY (director)
	REFERENCES director (id);

ALTER TABLE movie ADD CONSTRAINT information
	FOREIGN KEY (information)
	REFERENCES information (id);
	
ALTER TABLE movie ADD CONSTRAINT movie_genre
	FOREIGN KEY (movie_genre)
	REFERENCES movie_genre (id);

ALTER TABLE game ADD CONSTRAINT information
	FOREIGN KEY (information)
	REFERENCES information (id);
	
ALTER TABLE game ADD CONSTRAINT game_genre
	FOREIGN KEY (game_genre)
	REFERENCES game_genre (id);
	
ALTER TABLE review ADD CONSTRAINT _user
	FOREIGN KEY (_user)
	REFERENCES _user (id);

ALTER TABLE review ADD CONSTRAINT movie
	FOREIGN KEY (movie)
	REFERENCES movie (id);

ALTER TABLE review ADD CONSTRAINT game
	FOREIGN KEY (game)
	REFERENCES game (id);